In [1]:
import pandas as pd

df = pd.read_csv("../files/csv/sales_raw.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    2000 non-null   int64
 1   item        2000 non-null   str
 2   price       1744 non-null   str
 3   notes       2000 non-null   str
 4   status      2000 non-null   str
 5   event_time  2000 non-null   str
 6   sale_date   2000 non-null   str
dtypes: int64(1), str(6)
memory usage: 109.5 KB

In [2]:
df.head(10)

,order_id,item,price,notes,status,event_time,sale_date
0,2309,orange,12.5,Tempor do aliquip nisi irure sit aliqua ipsum ...,delivered,2025-08-14,2026-04-05
1,2206,banana,12.5,Commodo ut labore adipiscing reprehenderit lab...,delivered,2025-03-22,2025-10-28
2,2698,APPLE,100.0,Sed dolor laboris ea voluptate duis aute dolor...,shipped,2025-03-15,2025-06-25
3,2093,Banana,45.0,Dolore voluptate ullamco veniam nisi duis ea d...,packed,2025-11-19,2025-08-06
4,2342,Apple,22.99,Ut tempor eiusmod quis tempor nostrud irure ma...,ordered,2025-06-06,2025-06-13
5,2622,mango,8.0,Dolore voluptate minim reprehenderit aute lore...,ordered,2025-10-28,2026-03-22
6,1323,Apple,12.5,Aute tempor ad elit dolor aute incididunt ulla...,ordered,2025-11-28,2026-05-16
7,1039,orange,100.0,Commodo eiusmod eiusmod quis sit aliquip conse...,delivered,2025-08-05,2025-07-25
8,2460,banana,22.99,Ullamco aliqua minim consectetur do labore nos...,shipped,2025-03-14,2025-09-01
9,1570,Apple,NaN,Consectetur in quis enim ea commodo sed amet a...,ordered,2025-03-04,2026-02-17

In [3]:
df['price'] = df['price'].apply(pd.to_numeric, errors='coerce')
cols = ['event_time', 'sale_date']
df[cols] = df[cols].apply(pd.to_datetime, errors='coerce')
df['item'] = df['item'].str.title()
df['status'] = df['status'].str.lower()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    2000 non-null   int64
 1   item        2000 non-null   str
 2   price       1503 non-null   float64
 3   notes       2000 non-null   str
 4   status      2000 non-null   str
 5   event_time  2000 non-null   datetime64[us]
 6   sale_date   2000 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(1), int64(1), str(3)
memory usage: 109.5 KB

In [4]:
df.head(10)

,order_id,item,price,notes,status,event_time,sale_date
0,2309,Orange,12.50,Tempor do aliquip nisi irure sit aliqua ipsum ...,delivered,2025-08-14,2026-04-05
1,2206,Banana,12.50,Commodo ut labore adipiscing reprehenderit lab...,delivered,2025-03-22,2025-10-28
2,2698,Apple,100.00,Sed dolor laboris ea voluptate duis aute dolor...,shipped,2025-03-15,2025-06-25
3,2093,Banana,45.00,Dolore voluptate ullamco veniam nisi duis ea d...,packed,2025-11-19,2025-08-06
4,2342,Apple,22.99,Ut tempor eiusmod quis tempor nostrud irure ma...,ordered,2025-06-06,2025-06-13
5,2622,Mango,8.00,Dolore voluptate minim reprehenderit aute lore...,ordered,2025-10-28,2026-03-22
6,1323,Apple,12.50,Aute tempor ad elit dolor aute incididunt ulla...,ordered,2025-11-28,2026-05-16
7,1039,Orange,100.00,Commodo eiusmod eiusmod quis sit aliquip conse...,delivered,2025-08-05,2025-07-25
8,2460,Banana,22.99,Ullamco aliqua minim consectetur do labore nos...,shipped,2025-03-14,2025-09-01
9,1570,Apple,NaN,Consectetur in quis enim ea commodo sed amet a...,ordered,2025-03-04,2026-02-17

In [217]:
nan = df.groupby(['item', 'status'])['price'].transform('mean')
df['price'] = df['price'].fillna(nan)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    2000 non-null   int64
 1   item        2000 non-null   str
 2   price       2000 non-null   float64
 3   notes       2000 non-null   str
 4   status      2000 non-null   str
 5   event_time  2000 non-null   datetime64[us]
 6   sale_date   2000 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(1), int64(1), str(3)
memory usage: 109.5 KB

In [6]:
duplicates = df.duplicated(['order_id', 'item', 'price', 'status'])
duplicates.index = df['order_id']
duplicates[duplicates.values == True]

order_id
1181    True
1262    True
2413    True
2337    True
2133    True
1788    True
dtype: bool