In [87]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('files/csv/superstore_extract.csv')

# 1. View top/bottom rows
print(df.head(5))
print(df.tail(5))

# 2. Schema breakdown (Equivalent to DESCRIBE table_name; in SQL)
print(df.info())

# 3. Shape of DataFrame (Rows, Columns)
print(df.shape)  # Returns tuple: (2000, 6)

# 4. Statistical Summary (Mean, Min, Max, Quantiles)
print(df.describe())

   order_id    sales  profit  discount  quantity         category
0      2824   134.80  -87.46      0.18         2  Office Supplies
1      9935   443.82  132.88      0.02         4       Technology
2      9279  3014.07  341.87      0.57         9        Furniture
3      4611  2251.55  -82.71      0.70         3  Office Supplies
4      7924  1707.85 -266.78      0.77         6       Technology
      order_id    sales  profit  discount  quantity         category
1995      8235  2455.57  683.45      0.55         9        Furniture
1996      6704   898.28  799.21      0.68         6  Office Supplies
1997      7948  1076.76  339.69      0.80         4        Furniture
1998      7130   903.24  621.44      0.01         8        Furniture
1999      9618   982.49  379.28      0.26         6        Furniture
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  2000 non-null   int64
 1   sales     2000 non-null   float64
 2   profit    2000 non-null   float64
 3   discount  2000 non-null   float64
 4   quantity  2000 non-null   int64
 5   category  2000 non-null   str
dtypes: float64(3), int64(2), str(1)
memory usage: 93.9 KB
None
(2000, 6)
          order_id        sales       profit     discount     quantity
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000
mean   5573.502500  2461.219125   249.537745     0.409685     5.492000
std    2608.304141  1455.758619   427.599360     0.232331     2.868109
min    1003.000000    12.670000  -499.950000     0.000000     1.000000
25%    3325.750000  1176.327500  -114.120000     0.210000     3.000000
50%    5614.500000  2449.315000   248.990000     0.410000     5.000000
75%    7834.500000  3739.137500   606.855000     0.620000     8.000000
max    9987.000000  4999.770000   999.960000     0.800000    10.000000

In [91]:
robust_report = df.pivot_table(
    index='category',
    columns='quantity',
    values='sales',
    aggfunc='sum',
    fill_value=0,
    margins=True  # Injects Grand Totals automatically!
)
print(robust_report.head(10))

quantity                 1          2          3          4          5  \
category
Furniture        146384.30  147670.38  141471.96  124752.97  132548.65
Office Supplies  155257.40  162021.85  180506.76  133392.72  177626.58
Technology       174083.84  159935.06  170335.20  179978.48  177758.31
All              475725.54  469627.29  492313.92  438124.17  487933.54

quantity                 6          7          8          9         10  \
category
Furniture        205076.07  158056.33  163164.95  193773.26  153522.49
Office Supplies  125056.93  204225.93  190679.71  145979.61  195584.90
Technology       150463.07  158231.50  148072.54  172818.37  194008.13
All              480596.07  520513.76  501917.20  512571.24  543115.52

quantity                All
category
Furniture        1566421.36
Office Supplies  1670332.39
Technology       1685684.50
All              4922438.25

In [33]:
# Single column (returns a Series)
sales_series = df['sales']
print(sales_series)
# Multiple columns (returns a DataFrame)
selected_df = df[['order_id', 'sales', 'category']]
print(selected_df)

0        134.80
1        443.82
2       3014.07
3       2251.55
4       1707.85
         ...
1995    2455.57
1996     898.28
1997    1076.76
1998     903.24
1999     982.49
Name: sales, Length: 2000, dtype: float64
      order_id    sales         category
0         2824   134.80  Office Supplies
1         9935   443.82       Technology
2         9279  3014.07        Furniture
3         4611  2251.55  Office Supplies
4         7924  1707.85       Technology
...        ...      ...              ...
1995      8235  2455.57        Furniture
1996      6704   898.28  Office Supplies
1997      7948  1076.76        Furniture
1998      7130   903.24        Furniture
1999      9618   982.49        Furniture

[2000 rows x 3 columns]

In [34]:
high_sales = df[df['sales'] > 3000]
print(high_sales)

      order_id    sales  profit  discount  quantity         category
2         9279  3014.07  341.87      0.57         9        Furniture
8         2307  4278.04  799.73      0.30         8  Office Supplies
11        4598  3426.23  764.28      0.62         4       Technology
16        1771  4306.90 -270.74      0.13         7  Office Supplies
18        1188  3404.61 -328.17      0.71         5  Office Supplies
...        ...      ...     ...       ...       ...              ...
1984      1231  4640.12  -88.13      0.66         7  Office Supplies
1988      5542  4833.63  605.90      0.49         8       Technology
1991      9383  4038.10  138.11      0.38         5  Office Supplies
1993      6107  4194.86  -24.54      0.06        10       Technology
1994      3721  4727.99  750.41      0.57         7  Office Supplies

[796 rows x 6 columns]

In [35]:
tech_high_sales = df[(df['sales'] > 3000) & (df['category'] == 'Technology')]
print(tech_high_sales)
furniture_or_loss = df[(df['category'] == 'Furniture') | (df['profit'] < 0)]
print(furniture_or_loss)

      order_id    sales  profit  discount  quantity    category
11        4598  3426.23  764.28      0.62         4  Technology
24        9727  3831.51 -307.41      0.38         9  Technology
35        5092  4373.68 -386.92      0.65         9  Technology
36        1828  3264.20  310.88      0.01         2  Technology
39        7930  3485.99  595.76      0.63         8  Technology
...        ...      ...     ...       ...       ...         ...
1951      2478  3904.36   -0.07      0.28         9  Technology
1957      3025  4066.85   66.79      0.32         5  Technology
1980      9591  3578.26  210.81      0.25         3  Technology
1988      5542  4833.63  605.90      0.49         8  Technology
1993      6107  4194.86  -24.54      0.06        10  Technology

[281 rows x 6 columns]
      order_id    sales  profit  discount  quantity         category
0         2824   134.80  -87.46      0.18         2  Office Supplies
2         9279  3014.07  341.87      0.57         9        Furniture
3         4611  2251.55  -82.71      0.70         3  Office Supplies
4         7924  1707.85 -266.78      0.77         6       Technology
6         8527  2685.78  959.67      0.30         9        Furniture
...        ...      ...     ...       ...       ...              ...
1993      6107  4194.86  -24.54      0.06        10       Technology
1995      8235  2455.57  683.45      0.55         9        Furniture
1997      7948  1076.76  339.69      0.80         4        Furniture
1998      7130   903.24  621.44      0.01         8        Furniture
1999      9618   982.49  379.28      0.26         6        Furniture

[1084 rows x 6 columns]

In [36]:
categories = ['Furniture', 'Technology']
filtered_cats = df[df['category'].isin(categories)]
print(filtered_cats)

      order_id    sales  profit  discount  quantity    category
1         9935   443.82  132.88      0.02         4  Technology
2         9279  3014.07  341.87      0.57         9   Furniture
4         7924  1707.85 -266.78      0.77         6  Technology
5         2519  1905.84   38.47      0.28         5  Technology
6         8527  2685.78  959.67      0.30         9   Furniture
...        ...      ...     ...       ...       ...         ...
1993      6107  4194.86  -24.54      0.06        10  Technology
1995      8235  2455.57  683.45      0.55         9   Furniture
1997      7948  1076.76  339.69      0.80         4   Furniture
1998      7130   903.24  621.44      0.01         8   Furniture
1999      9618   982.49  379.28      0.26         6   Furniture

[1317 rows x 6 columns]

In [37]:
mid_range_sales = df[df['sales'].between(1000, 2000)]
print(mid_range_sales)

      order_id    sales  profit  discount  quantity         category
4         7924  1707.85 -266.78      0.77         6       Technology
5         2519  1905.84   38.47      0.28         5       Technology
13        6155  1071.01  248.85      0.71         8       Technology
15        7543  1816.36  995.99      0.11         8       Technology
17        2040  1929.99  393.83      0.37         5  Office Supplies
...        ...      ...     ...       ...       ...              ...
1970      1598  1614.00  347.97      0.33         1        Furniture
1972      4862  1615.97  563.30      0.41         2       Technology
1985      6009  1842.70  650.48      0.75         9  Office Supplies
1992      2921  1211.46   89.87      0.62         8        Furniture
1997      7948  1076.76  339.69      0.80         4        Furniture

[392 rows x 6 columns]

In [39]:
df = df.rename(columns={
    'sales': 'total_sales',
    'profit': 'net_profit'
})

In [40]:
# Aggregations across entire series
total_sales = df['total_sales'].sum()
print(total_sales)
average_profit = df['net_profit'].mean()
print(average_profit)
median_discount = df['discount'].median()
print(median_discount)
max_quantity = df['quantity'].max()
print(max_quantity)
# Frequency counts of unique values (SQL: GROUP BY category COUNT(*))
category_distribution = df['category'].value_counts()
print(category_distribution)

4922438.25
249.537745
0.41
10
category
Office Supplies    683
Technology         679
Furniture          638
Name: count, dtype: int64

In [41]:
# SQL: SELECT category, AVG(total_sales) FROM table GROUP BY category;
avg_sales_by_cat = df.groupby('category')['total_sales'].mean()
print(avg_sales_by_cat)

category
Furniture          2455.205893
Office Supplies    2445.581830
Technology         2482.598675
Name: total_sales, dtype: float64

In [42]:
# SQL: 
# SELECT category, SUM(total_sales) AS revenue, AVG(net_profit) AS avg_profit, COUNT(order_id) AS orders 
# FROM table GROUP BY category;

grouped_summary = df.groupby('category').agg(
    revenue=('total_sales', 'sum'),
    avg_profit=('net_profit', 'mean'),
    orders=('order_id', 'count')
).reset_index()

print(grouped_summary)

          category     revenue  avg_profit  orders
0        Furniture  1566421.36  248.672320     638
1  Office Supplies  1670332.39  235.225271     683
2       Technology  1685684.50  264.747703     679

In [44]:
# SQL: SELECT * FROM table GROUP BY category HAVING SUM(total_sales) > 1600000;
large_categories_df = df.groupby('category').filter(lambda x: x['total_sales'].sum() > 1600000)
print(large_categories_df)

      order_id  total_sales  net_profit  discount  quantity         category
0         2824       134.80      -87.46      0.18         2  Office Supplies
1         9935       443.82      132.88      0.02         4       Technology
3         4611      2251.55      -82.71      0.70         3  Office Supplies
4         7924      1707.85     -266.78      0.77         6       Technology
5         2519      1905.84       38.47      0.28         5       Technology
...        ...          ...         ...       ...       ...              ...
1990      3348       832.44      811.92      0.26         1       Technology
1991      9383      4038.10      138.11      0.38         5  Office Supplies
1993      6107      4194.86      -24.54      0.06        10       Technology
1994      3721      4727.99      750.41      0.57         7  Office Supplies
1996      6704       898.28      799.21      0.68         6  Office Supplies

[1362 rows x 6 columns]

In [48]:
# SQL: SELECT *, AVG(total_sales) OVER(PARTITION BY category) AS category_avg_sales FROM table;

df['category_avg_sales'] = df.groupby('category')['total_sales'].transform('mean')

# Calculate the contribution percentage of each individual sale to its parent category
df['sale_percentage_of_category'] = (df['total_sales'] / df.groupby('category')['total_sales'].transform('sum')) * 100

print(df[['category', 'total_sales', 'category_avg_sales', 'sale_percentage_of_category']].sort_values(by='category').head(10))

       category  total_sales  category_avg_sales  sale_percentage_of_category
1999  Furniture       982.49         2455.205893                     0.062722
583   Furniture      4604.97         2455.205893                     0.293980
1382  Furniture      1698.53         2455.205893                     0.108434
1381  Furniture       888.63         2455.205893                     0.056730
590   Furniture      2287.68         2455.205893                     0.146045
1374  Furniture       819.78         2455.205893                     0.052335
1373  Furniture      4261.52         2455.205893                     0.272055
593   Furniture      1727.80         2455.205893                     0.110302
1371  Furniture       985.08         2455.205893                     0.062887
1370  Furniture       296.02         2455.205893                     0.018898

In [49]:
# Vectorized multi-conditional logic (SQL: CASE WHEN ... THEN ... ELSE ...)
conditions = [
    (df['net_profit'] > 500),
    (df['net_profit'] >= 0) & (df['net_profit'] <= 500),
    (df['net_profit'] < 0)
]
choices = ['High Profit', 'Stable', 'Loss-Making']

df['performance_tier'] = np.select(conditions, choices, default='Unknown')

# Custom python lambda logic via apply
df['adjusted_quantity'] = df['quantity'].apply(lambda x: x + 1 if x % 2 == 0 else x)
df

,order_id,total_sales,net_profit,discount,quantity,category,category_avg_sales,sale_percentage_of_category,performance_tier,adjusted_quantity
0,2824,134.80,-87.46,0.18,2,Office Supplies,2445.581830,0.008070,Loss-Making,3
1,9935,443.82,132.88,0.02,4,Technology,2482.598675,0.026329,Stable,5
2,9279,3014.07,341.87,0.57,9,Furniture,2455.205893,0.192418,Stable,9
3,4611,2251.55,-82.71,0.70,3,Office Supplies,2445.581830,0.134797,Loss-Making,3
4,7924,1707.85,-266.78,0.77,6,Technology,2482.598675,0.101315,Loss-Making,7
...,...,...,...,...,...,...,...,...,...,...
1995,8235,2455.57,683.45,0.55,9,Furniture,2455.205893,0.156763,High Profit,9
1996,6704,898.28,799.21,0.68,6,Office Supplies,2445.581830,0.053779,High Profit,7
1997,7948,1076.76,339.69,0.80,4,Furniture,2455.205893,0.068740,Stable,5
1998,7130,903.24,621.44,0.01,8,Furniture,2455.205893,0.057663,High Profit,9
1999,9618,982.49,379.28,0.26,6,Furniture,2455.205893,0.062722,Stable,7

In [52]:
# SQL: ORDER BY category ASC, total_sales DESC
df_sorted = df.sort_values(by=['category', 'total_sales'], ascending=[True, False])
df_sorted

,order_id,total_sales,net_profit,discount,quantity,category,category_avg_sales,sale_percentage_of_category,performance_tier,adjusted_quantity
1331,7228,4996.22,763.66,0.17,9,Furniture,2455.205893,0.318958,High Profit,9
370,9255,4967.48,-148.76,0.73,10,Furniture,2455.205893,0.317123,Loss-Making,11
1502,8125,4966.87,-456.17,0.74,6,Furniture,2455.205893,0.317084,Loss-Making,7
1670,9459,4961.47,413.11,0.42,6,Furniture,2455.205893,0.316739,Stable,7
1912,3735,4949.77,-301.43,0.69,7,Furniture,2455.205893,0.315992,Loss-Making,7
...,...,...,...,...,...,...,...,...,...,...
1731,9953,35.02,282.62,0.20,2,Technology,2482.598675,0.002077,Stable,3
53,1722,27.69,656.68,0.51,5,Technology,2482.598675,0.001643,High Profit,5
1495,4079,25.61,457.11,0.75,6,Technology,2482.598675,0.001519,Stable,7
126,3564,23.35,175.76,0.48,5,Technology,2482.598675,0.001385,Stable,5
1989,3754,23.33,-152.25,0.17,10,Technology,2482.598675,0.001384,Loss-Making,11

In [57]:
pivot_df = df.pivot_table(
    index='category', 
    values=['total_sales', 'net_profit'], 
    aggfunc={'total_sales': 'sum', 'net_profit': 'mean'}
)
pivot_df

                 net_profit  total_sales
category
Furniture        248.672320   1566421.36
Office Supplies  235.225271   1670332.39
Technology       264.747703   1685684.50
All              249.537745   4922438.25

In [62]:
# 1. ROW_NUMBER() OVER(PARTITION BY category ORDER BY sales DESC)
df['row_number'] = df.groupby('category')['total_sales'].rank(method='first', ascending=False)
df.sort_values(by=['category','row_number'],ascending=[True, False])

,order_id,total_sales,net_profit,discount,quantity,category,category_avg_sales,sale_percentage_of_category,performance_tier,adjusted_quantity,row_number
1593,1669,12.67,490.65,0.26,5,Furniture,2455.205893,0.000809,Stable,5,638.0
1330,3742,12.71,900.26,0.39,10,Furniture,2455.205893,0.000811,High Profit,11,637.0
67,8144,18.44,888.36,0.43,4,Furniture,2455.205893,0.001177,High Profit,5,636.0
38,7209,20.76,85.63,0.74,8,Furniture,2455.205893,0.001325,Stable,9,635.0
503,9336,22.82,788.03,0.01,1,Furniture,2455.205893,0.001457,High Profit,1,634.0
...,...,...,...,...,...,...,...,...,...,...,...
891,8046,4978.47,963.67,0.12,10,Technology,2482.598675,0.295338,High Profit,11,5.0
688,8780,4983.19,735.53,0.78,1,Technology,2482.598675,0.295618,High Profit,1,4.0
1401,3258,4992.04,628.58,0.59,5,Technology,2482.598675,0.296143,High Profit,5,3.0
134,1339,4997.87,508.42,0.22,1,Technology,2482.598675,0.296489,High Profit,1,2.0
1531,8932,4999.77,554.11,0.24,3,Technology,2482.598675,0.296602,High Profit,3,1.0

In [64]:
# Grouping by multiple dimensions creates a MultiIndex DataFrame
multi_df = df.groupby(['category', 'quantity']).agg({'total_sales': 'mean', 'net_profit': 'sum'})
print(multi_df.head())

# 1. Slicing a MultiIndex using pd.IndexSlice (SQL: Filtering on composite keys)
# Get 'Furniture' records where quantity is between 5 and 7
idx = pd.IndexSlice
furniture_slice = multi_df.loc[idx['Furniture', 5:7], :]
print(furniture_slice)

                    total_sales  net_profit
category  quantity
Furniture 1         2252.066154    23824.77
          2         2502.887797    18157.82
          3         2176.491692    16106.98
          4         2045.130656    14161.27
          5         2325.414912    12319.31
                    total_sales  net_profit
category  quantity
Furniture 5         2325.414912    12319.31
          6         2629.180385    17308.39
          7         2549.295645    11839.61

In [65]:
# 2. Flattening the MultiIndex columns (Crucial after running complex .agg features)
# If your agg created nested columns like ('sales', 'mean'), flatten them:
multi_df.columns = ['_'.join(col).strip() for col in multi_df.columns.values]
multi_df = multi_df.reset_index()
print(multi_df)

           category  quantity  t_o_t_a_l___s_a_l_e_s  n_e_t___p_r_o_f_i_t
0         Furniture         1            2252.066154             23824.77
1         Furniture         2            2502.887797             18157.82
2         Furniture         3            2176.491692             16106.98
3         Furniture         4            2045.130656             14161.27
4         Furniture         5            2325.414912             12319.31
5         Furniture         6            2629.180385             17308.39
6         Furniture         7            2549.295645             11839.61
7         Furniture         8            2589.919841              9658.72
8         Furniture         9            2768.189429             22462.49
9         Furniture        10            2646.939483             12813.58
10  Office Supplies         1            2388.575385             22188.40
11  Office Supplies         2            2531.591406             12236.46
12  Office Supplies         3            2406.756800             20376.30
13  Office Supplies         4            2382.012857             11828.18
14  Office Supplies         5            2248.437722             12202.36
15  Office Supplies         6            2359.564717             14042.29
16  Office Supplies         7            2552.824125             22059.73
17  Office Supplies         8            2612.050822             16672.29
18  Office Supplies         9            2280.931406             11453.67
19  Office Supplies        10            2643.039189             17599.18
20       Technology         1            2384.710137             16858.66
21       Technology         2            2460.539385             16729.40
22       Technology         3            2365.766667             20665.57
23       Technology         4            2337.382857             23559.39
24       Technology         5            2278.952692             17796.80
25       Technology         6            2426.823710             19996.28
26       Technology         7            2593.959016             15801.94
27       Technology         8            2509.704068             14167.31
28       Technology         9            2787.393065             14949.98
29       Technology        10            2771.544714             19238.36

In [69]:
df['sales_cleaned'] = df['total_sales'].mask(df['total_sales'] > 4000, np.nan)
df

,order_id,total_sales,net_profit,discount,quantity,category,category_avg_sales,sale_percentage_of_category,performance_tier,adjusted_quantity,row_number,sales_cleaned
0,2824,134.80,-87.46,0.18,2,Office Supplies,2445.581830,0.008070,Loss-Making,3,658.0,134.80
1,9935,443.82,132.88,0.02,4,Technology,2482.598675,0.026329,Stable,5,623.0,443.82
2,9279,3014.07,341.87,0.57,9,Furniture,2455.205893,0.192418,Stable,9,247.0,3014.07
3,4611,2251.55,-82.71,0.70,3,Office Supplies,2445.581830,0.134797,Loss-Making,3,369.0,2251.55
4,7924,1707.85,-266.78,0.77,6,Technology,2482.598675,0.101315,Loss-Making,7,429.0,1707.85
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,8235,2455.57,683.45,0.55,9,Furniture,2455.205893,0.156763,High Profit,9,321.0,2455.57
1996,6704,898.28,799.21,0.68,6,Office Supplies,2445.581830,0.053779,High Profit,7,555.0,898.28
1997,7948,1076.76,339.69,0.80,4,Furniture,2455.205893,0.068740,Stable,5,479.0,1076.76
1998,7130,903.24,621.44,0.01,8,Furniture,2455.205893,0.057663,High Profit,9,509.0,903.24
1999,9618,982.49,379.28,0.26,6,Furniture,2455.205893,0.062722,Stable,7,493.0,982.49

In [71]:
criteria = [
    (df['total_sales'] > 3000) & (df['net_profit'] > 500),
    (df['total_sales'] > 3000) & (df['net_profit'] <= 500),
    (df['total_sales'] <= 3000)
]
outputs = ['High Yield', 'High Risk Volume', 'Standard']
df['deal_segment'] = np.select(criteria, outputs, default='Unclassified')
df

,order_id,total_sales,net_profit,discount,quantity,category,category_avg_sales,sale_percentage_of_category,performance_tier,adjusted_quantity,row_number,sales_cleaned,deal_segment
0,2824,134.80,-87.46,0.18,2,Office Supplies,2445.581830,0.008070,Loss-Making,3,658.0,134.80,Standard
1,9935,443.82,132.88,0.02,4,Technology,2482.598675,0.026329,Stable,5,623.0,443.82,Standard
2,9279,3014.07,341.87,0.57,9,Furniture,2455.205893,0.192418,Stable,9,247.0,3014.07,High Risk Volume
3,4611,2251.55,-82.71,0.70,3,Office Supplies,2445.581830,0.134797,Loss-Making,3,369.0,2251.55,Standard
4,7924,1707.85,-266.78,0.77,6,Technology,2482.598675,0.101315,Loss-Making,7,429.0,1707.85,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,8235,2455.57,683.45,0.55,9,Furniture,2455.205893,0.156763,High Profit,9,321.0,2455.57,Standard
1996,6704,898.28,799.21,0.68,6,Office Supplies,2445.581830,0.053779,High Profit,7,555.0,898.28,Standard
1997,7948,1076.76,339.69,0.80,4,Furniture,2455.205893,0.068740,Stable,5,479.0,1076.76,Standard
1998,7130,903.24,621.44,0.01,8,Furniture,2455.205893,0.057663,High Profit,9,509.0,903.24,Standard
1999,9618,982.49,379.28,0.26,6,Furniture,2455.205893,0.062722,Stable,7,493.0,982.49,Standard

In [73]:
# 1. pd.cut: Equal-width bins (divides the value range into equal parts)
# Divides the min-max sales range into 3 equal spans
df['sales_equal_width'] = pd.cut(df['total_sales'], bins=3, labels=['Low Range', 'Mid Range', 'High Range'])

# 2. pd.qcut: Equal-frequency bins (Sample Quantiles)
# Ensures that an equal number of rows/orders end up in each bucket (Terciles)
df['sales_percentile_bucket'] = pd.qcut(df['total_sales'], q=3, labels=['Tier 3', 'Tier 2', 'Tier 1'])

df

,order_id,total_sales,net_profit,discount,quantity,category,category_avg_sales,sale_percentage_of_category,performance_tier,adjusted_quantity,row_number,sales_cleaned,deal_segment,sales_equal_width,sales_percentile_bucket
0,2824,134.80,-87.46,0.18,2,Office Supplies,2445.581830,0.008070,Loss-Making,3,658.0,134.80,Standard,Low Range,Tier 3
1,9935,443.82,132.88,0.02,4,Technology,2482.598675,0.026329,Stable,5,623.0,443.82,Standard,Low Range,Tier 3
2,9279,3014.07,341.87,0.57,9,Furniture,2455.205893,0.192418,Stable,9,247.0,3014.07,High Risk Volume,Mid Range,Tier 2
3,4611,2251.55,-82.71,0.70,3,Office Supplies,2445.581830,0.134797,Loss-Making,3,369.0,2251.55,Standard,Mid Range,Tier 2
4,7924,1707.85,-266.78,0.77,6,Technology,2482.598675,0.101315,Loss-Making,7,429.0,1707.85,Standard,Mid Range,Tier 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,8235,2455.57,683.45,0.55,9,Furniture,2455.205893,0.156763,High Profit,9,321.0,2455.57,Standard,Mid Range,Tier 2
1996,6704,898.28,799.21,0.68,6,Office Supplies,2445.581830,0.053779,High Profit,7,555.0,898.28,Standard,Low Range,Tier 3
1997,7948,1076.76,339.69,0.80,4,Furniture,2455.205893,0.068740,Stable,5,479.0,1076.76,Standard,Low Range,Tier 3
1998,7130,903.24,621.44,0.01,8,Furniture,2455.205893,0.057663,High Profit,9,509.0,903.24,Standard,Low Range,Tier 3
1999,9618,982.49,379.28,0.26,6,Furniture,2455.205893,0.062722,Stable,7,493.0,982.49,Standard,Low Range,Tier 3

In [75]:
# 1. Pandas .where(): Keeps values where condition is TRUE, otherwise replaces with alternative
# SQL: CASE WHEN sales > 1000 THEN sales ELSE 0 END
df['sales_clipped'] = df['total_sales'].where(df['total_sales'] > 1000, 0)

# 2. Pandas .mask(): Replaces values where condition is TRUE (Opposite of .where())
# Hides negative profit records by setting them to NaN
df['clean_profit'] = df['net_profit'].mask(df['net_profit'] < 0, np.nan)

# 3. NumPy np.where(): Binary choice assignment (True choice, False choice)
df['profit_status'] = np.where(df['net_profit'] > 0, 'Profitable', 'Loss')
df

,order_id,total_sales,net_profit,discount,quantity,category,category_avg_sales,sale_percentage_of_category,performance_tier,adjusted_quantity,row_number,sales_cleaned,deal_segment,sales_equal_width,sales_percentile_bucket,sales_clipped,clean_profit,profit_status
0,2824,134.80,-87.46,0.18,2,Office Supplies,2445.581830,0.008070,Loss-Making,3,658.0,134.80,Standard,Low Range,Tier 3,0.00,NaN,Loss
1,9935,443.82,132.88,0.02,4,Technology,2482.598675,0.026329,Stable,5,623.0,443.82,Standard,Low Range,Tier 3,0.00,132.88,Profitable
2,9279,3014.07,341.87,0.57,9,Furniture,2455.205893,0.192418,Stable,9,247.0,3014.07,High Risk Volume,Mid Range,Tier 2,3014.07,341.87,Profitable
3,4611,2251.55,-82.71,0.70,3,Office Supplies,2445.581830,0.134797,Loss-Making,3,369.0,2251.55,Standard,Mid Range,Tier 2,2251.55,NaN,Loss
4,7924,1707.85,-266.78,0.77,6,Technology,2482.598675,0.101315,Loss-Making,7,429.0,1707.85,Standard,Mid Range,Tier 2,1707.85,NaN,Loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,8235,2455.57,683.45,0.55,9,Furniture,2455.205893,0.156763,High Profit,9,321.0,2455.57,Standard,Mid Range,Tier 2,2455.57,683.45,Profitable
1996,6704,898.28,799.21,0.68,6,Office Supplies,2445.581830,0.053779,High Profit,7,555.0,898.28,Standard,Low Range,Tier 3,0.00,799.21,Profitable
1997,7948,1076.76,339.69,0.80,4,Furniture,2455.205893,0.068740,Stable,5,479.0,1076.76,Standard,Low Range,Tier 3,1076.76,339.69,Profitable
1998,7130,903.24,621.44,0.01,8,Furniture,2455.205893,0.057663,High Profit,9,509.0,903.24,Standard,Low Range,Tier 3,0.00,621.44,Profitable
1999,9618,982.49,379.28,0.26,6,Furniture,2455.205893,0.062722,Stable,7,493.0,982.49,Standard,Low Range,Tier 3,0.00,379.28,Profitable

In [79]:
target_sequences = range(1000, 1010)

# 2. Aligning two DataFrames with mismatched axes
df1 = df.iloc[0:10, :]
df2 = df.iloc[5:15, :]
aligned_df1, aligned_df2 = df1.align(df2, join='outer', axis=0)
print(aligned_df1)

    order_id  total_sales  net_profit  discount  quantity         category  \
0     2824.0       134.80      -87.46      0.18       2.0  Office Supplies
1     9935.0       443.82      132.88      0.02       4.0       Technology
2     9279.0      3014.07      341.87      0.57       9.0        Furniture
3     4611.0      2251.55      -82.71      0.70       3.0  Office Supplies
4     7924.0      1707.85     -266.78      0.77       6.0       Technology
5     2519.0      1905.84       38.47      0.28       5.0       Technology
6     8527.0      2685.78      959.67      0.30       9.0        Furniture
7     6925.0      2890.99      556.86      0.04       4.0        Furniture
8     2307.0      4278.04      799.73      0.30       8.0  Office Supplies
9     6977.0       821.64       32.91      0.54       2.0  Office Supplies
10       NaN          NaN         NaN       NaN       NaN              NaN
11       NaN          NaN         NaN       NaN       NaN              NaN
12       NaN          NaN         NaN       NaN       NaN              NaN
13       NaN          NaN         NaN       NaN       NaN              NaN
14       NaN          NaN         NaN       NaN       NaN              NaN

    category_avg_sales  sale_percentage_of_category performance_tier  \
0          2445.581830                     0.008070      Loss-Making
1          2482.598675                     0.026329           Stable
2          2455.205893                     0.192418           Stable
3          2445.581830                     0.134797      Loss-Making
4          2482.598675                     0.101315      Loss-Making
5          2482.598675                     0.113060           Stable
6          2455.205893                     0.171460      High Profit
7          2455.205893                     0.184560      High Profit
8          2445.581830                     0.256119      High Profit
9          2445.581830                     0.049190           Stable
10                 NaN                          NaN              NaN
11                 NaN                          NaN              NaN
12                 NaN                          NaN              NaN
13                 NaN                          NaN              NaN
14                 NaN                          NaN              NaN

    adjusted_quantity  row_number  sales_cleaned      deal_segment  \
0                 3.0       658.0         134.80          Standard
1                 5.0       623.0         443.82          Standard
2                 9.0       247.0        3014.07  High Risk Volume
3                 3.0       369.0        2251.55          Standard
4                 7.0       429.0        1707.85          Standard
5                 5.0       400.0        1905.84          Standard
6                 9.0       284.0        2685.78          Standard
7                 5.0       255.0        2890.99          Standard
8                 9.0        87.0            NaN        High Yield
9                 3.0       566.0         821.64          Standard
10                NaN         NaN            NaN               NaN
11                NaN         NaN            NaN               NaN
12                NaN         NaN            NaN               NaN
13                NaN         NaN            NaN               NaN
14                NaN         NaN            NaN               NaN

   sales_equal_width sales_percentile_bucket  sales_clipped  clean_profit  \
0          Low Range                  Tier 3           0.00           NaN
1          Low Range                  Tier 3           0.00        132.88
2          Mid Range                  Tier 2        3014.07        341.87
3          Mid Range                  Tier 2        2251.55           NaN
4          Mid Range                  Tier 2        1707.85           NaN
5          Mid Range                  Tier 2        1905.84         38.47
6          Mid Range                  Tier 2        2685.78        959.67
7          Mid Range                  Tier 2        2890.99        556.86
8         High Range                  Tier 1        4278.04        799.73
9          Low Range                  Tier 3           0.00         32.91
10               NaN                     NaN            NaN           NaN
11               NaN                     NaN            NaN           NaN
12               NaN                     NaN            NaN           NaN
13               NaN                     NaN            NaN           NaN
14               NaN                     NaN            NaN           NaN

   profit_status
0           Loss
1     Profitable
2     Profitable
3           Loss
4           Loss
5     Profitable
6     Profitable
7     Profitable
8     Profitable
9     Profitable
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN

In [81]:
# Create an explicit logical ordering tier
custom_category_order = ['Office Supplies', 'Technology', 'Furniture']

# Convert the column to a CategoricalDtype specifying logical sorting rules
df['category'] = pd.Categorical(df['category'], categories=custom_category_order, ordered=True)

# Now sorting will automatically respect your custom list arrangement instead of alphabetical order
df_custom_sorted = df.sort_values('category')
df_custom_sorted

,order_id,total_sales,net_profit,discount,quantity,category,category_avg_sales,sale_percentage_of_category,performance_tier,adjusted_quantity,row_number,sales_cleaned,deal_segment,sales_equal_width,sales_percentile_bucket,sales_clipped,clean_profit,profit_status
0,2824,134.80,-87.46,0.18,2,Office Supplies,2445.581830,0.008070,Loss-Making,3,658.0,134.80,Standard,Low Range,Tier 3,0.00,NaN,Loss
1444,6181,69.79,-180.85,0.18,5,Office Supplies,2445.581830,0.004178,Loss-Making,5,671.0,69.79,Standard,Low Range,Tier 3,0.00,NaN,Loss
1443,4807,1076.76,34.86,0.14,7,Office Supplies,2445.581830,0.064464,Stable,7,531.0,1076.76,Standard,Low Range,Tier 3,1076.76,34.86,Profitable
595,4688,3391.70,-96.37,0.33,1,Office Supplies,2445.581830,0.203055,Loss-Making,1,216.0,3391.70,High Risk Volume,High Range,Tier 1,3391.70,NaN,Loss
598,7168,4259.42,188.50,0.17,5,Office Supplies,2445.581830,0.255004,Stable,5,91.0,NaN,High Risk Volume,High Range,Tier 1,4259.42,188.50,Profitable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,5481,1054.82,660.31,0.46,3,Furniture,2455.205893,0.067339,High Profit,3,484.0,1054.82,Standard,Low Range,Tier 3,1054.82,660.31,Profitable
1422,1640,3689.08,-68.13,0.70,8,Furniture,2455.205893,0.235510,Loss-Making,9,169.0,3689.08,High Risk Volume,High Range,Tier 1,3689.08,NaN,Loss
614,6449,3158.85,-234.76,0.51,1,Furniture,2455.205893,0.201660,Loss-Making,1,229.0,3158.85,High Risk Volume,Mid Range,Tier 2,3158.85,NaN,Loss
1411,7404,4901.06,-193.69,0.31,9,Furniture,2455.205893,0.312883,Loss-Making,9,9.0,NaN,High Risk Volume,High Range,Tier 1,4901.06,NaN,Loss
1999,9618,982.49,379.28,0.26,6,Furniture,2455.205893,0.062722,Stable,7,493.0,982.49,Standard,Low Range,Tier 3,0.00,379.28,Profitable